# Generated by Django 2.2 on 2019-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_room_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='contact',
            field=models.BooleanField(default=False, help_text='가맹점일 경우 체크하시오.'),
        ),
    ]
